name: kit-backend

services:
  postgresql:
    image: postgres:15-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql: