// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeNonSerializedTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type AuthMeGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../src/controllers/auth/me.controller.ts').default['handle'], false>
}
type AuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../src/controllers/auth/login.controller.ts')['validator']>>
  response: MakeNonSerializedTuyauResponse<import('../src/controllers/auth/login.controller.ts').default['handle'], true>
}
type AuthLogoutDelete = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../src/controllers/auth/logout.controller.ts').default['handle'], false>
}
type HealthGetHead = {
  request: unknown
  response: MakeNonSerializedTuyauResponse<import('../src/controllers/health_checks.controller.ts').default['handle'], false>
}
export interface ApiDefinition {
  'auth': {
    'me': {
      '$url': {
      };
      '$get': AuthMeGetHead;
      '$head': AuthMeGetHead;
    };
    'login': {
      '$url': {
      };
      '$post': AuthLoginPost;
    };
    'logout': {
      '$url': {
      };
      '$delete': AuthLogoutDelete;
    };
  };
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
